# Generated by Django 5.2.17 on 2026-09-24 19:13

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('user', 'ผู้แจ้งเหตุ'), ('officer', 'เจ้าหน้าที่'), ('admin', 'ผู้ดูแลระบบ')], default='user', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('title', models.CharField(blank=True, help_text='คำนำหน้า เช่น นาย', max_length=20)),
                ('affiliation', models.CharField(blank=True, help_text='สังกัด/รหัสนักศึกษา แสดงใต้ชื่อในเมนู', max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='OfficerProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='officer', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('capacity', models.PositiveSmallIntegerField(default=3, help_text='จำนวนงานสูงสุดที่รับพร้อมกันได้')),
                ('on_duty', models.BooleanField(default=True, help_text='อยู่ในเวรตอนนี้หรือไม่')),
                ('shift_start', models.TimeField(default='08:00')),
                ('shift_end', models.TimeField(default='16:00')),
                ('cat', models.ForeignKey(help_text='ประเภทงานที่เชี่ยวชาญ', on_delete=django.db.models.deletion.PROTECT, related_name='officers', to='core.incidenttype')),
                ('zone', models.ForeignKey(help_text='พื้นที่รับผิดชอบหลัก', on_delete=django.db.models.deletion.PROTECT, related_name='officers', to='core.zone')),
            ],
            options={
                'verbose_name': 'โปรไฟล์เจ้าหน้าที่',
                'verbose_name_plural': 'โปรไฟล์เจ้าหน้าที่',
                'ordering': ['user__first_name'],
            },
        ),
    ]
