# Generated by Django 5.2.17 on 2026-09-24 19:13

import django.db.models.deletion
import django.utils.timezone
import incidents.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField(editable=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('place', models.CharField(help_text='สถานที่แบบละเอียด เช่น อาคารเรียนรวม 2 ห้อง 304', max_length=200)),
                ('note', models.TextField(blank=True, help_text='รายละเอียดเพิ่มเติมจากผู้แจ้ง')),
                ('reporter_name', models.CharField(blank=True, max_length=120)),
                ('reporter_phone', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'รอมอบหมาย'), ('progress', 'กำลังดำเนินการ'), ('review', 'รอตรวจผล'), ('done', 'ดำเนินการเสร็จสิ้น')], default='pending', max_length=20)),
                ('reported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('ack_at', models.DateTimeField(blank=True, help_text='เวลาที่ช่างกดรับทราบงาน', null=True)),
                ('submitted_at', models.DateTimeField(blank=True, help_text='เวลาที่ช่างส่งผลให้ตรวจ', null=True)),
                ('closed_at', models.DateTimeField(blank=True, help_text='เวลาที่ผู้ประสานงานปิดงาน', null=True)),
                ('assignee', models.ForeignKey(blank=True, limit_choices_to={'role': 'officer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='core.incidenttype')),
                ('pri', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='core.priority')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_incidents', to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='core.zone')),
            ],
            options={
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_updates', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='incidents.incident')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.ImageField(upload_to=incidents.models.incident_photo_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='incidents.incident')),
                ('update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='incidents.incidentupdate')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='StatusLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'รอมอบหมาย'), ('progress', 'กำลังดำเนินการ'), ('review', 'รอตรวจผล'), ('done', 'ดำเนินการเสร็จสิ้น')], max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='incidents.incident')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['status', 'reported_at'], name='incidents_i_status_cab3b2_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['assignee', 'status'], name='incidents_i_assigne_df572d_idx'),
        ),
    ]
