# Generated by Django 5.2.17 on 2026-09-24 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentType',
            fields=[
                ('key', models.SlugField(help_text='คีย์ที่ frontend ใช้ เช่น electric, plumbing', max_length=30, primary_key=True, serialize=False)),
                ('label', models.CharField(help_text='ชื่อที่แสดง เช่น ไฟฟ้า', max_length=60)),
                ('dept', models.CharField(help_text='ชื่อหน่วยงาน เช่น งานไฟฟ้า', max_length=80)),
                ('color', models.CharField(default='#5b6b7f', help_text='สีฮex เช่น #f26522', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'ประเภทเหตุ',
                'verbose_name_plural': 'ประเภทเหตุ',
                'ordering': ['order', 'key'],
            },
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('key', models.SlugField(help_text='emergency / urgent / normal', max_length=20, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=40)),
                ('rank', models.PositiveSmallIntegerField(default=0, help_text='เลขน้อย = เร่งด่วนกว่า ใช้เรียงคิว')),
                ('assign_sec', models.PositiveIntegerField(help_text='SLA: ต้องมอบหมายภายใน (วินาที)')),
                ('resolve_sec', models.PositiveIntegerField(help_text='SLA: ต้องแก้ไขเสร็จภายใน (วินาที)')),
                ('auto_assign', models.BooleanField(default=False, help_text='มอบหมายอัตโนมัติโดยไม่รอผู้ประสานงานยืนยัน')),
                ('note', models.TextField(blank=True, help_text='คำอธิบายที่แสดงให้ผู้แจ้งตอนเลือกระดับ')),
                ('examples', models.JSONField(blank=True, default=list, help_text='ตัวอย่างเหตุ แสดงให้ผู้แจ้งเลือกระดับได้ถูก')),
            ],
            options={
                'verbose_name': 'ระดับความเร่งด่วน',
                'verbose_name_plural': 'ระดับความเร่งด่วน',
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('name', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'พื้นที่',
                'verbose_name_plural': 'พื้นที่',
                'ordering': ['order', 'name'],
            },
        ),
    ]
